In [5]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5])
#or arr=np.array((1,2,3,4,5))
print(arr)
print(f'Type : {type(arr)}')

[1 2 3 4 5]
Type : <class 'numpy.ndarray'>


Dimentions in arrays :

In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(f'Dimention : {arr.ndim}')

[[1 2 3 4]
 [5 6 7 8]]
Dimention : 2


Accessing Elements : 

In [6]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(f'arr[1,2] : {arr[1,2]}') #outputs : 7

arr[1,2] : 7


Slicing Array :

In [25]:
arr=np.array([1,2,3,4,5])
print(f"slice :{arr[1:4]}") #return an array from index 1 to 3
#steps--
print(f"steps : {arr[::2]}") #print array elements with a step of two elements 

slice :[2 3 4]
steps : [1 3 5]


In [31]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(f"2D array slice : {arr[1,1:3]}") #outputs : 6,7
print(f"steps : {arr[0,1::2]}")

2D array slice : [6 7]
steps : [2 4]


Checking datatype : 

In [12]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
STRarr=np.array([['hi','hello'],['bye','cya']])
print(f"Arr DataType : {arr.dtype}")
print(f"STRArr DataType : {STRarr.dtype}")

Arr DataType : int64
STRArr DataType : <U5


Creating array with defined datatype :

In [11]:
arr=np.array([[1,2,3],[4,5,6]],dtype='S')
print(arr)
print(f"Datatype : {arr.dtype}")

[[b'1' b'2' b'3']
 [b'4' b'5' b'6']]
Datatype : |S1


Specifying Bytes : 

In [14]:
arr=np.array([[1,2,3],[4,5,6]],dtype='i4') #4 byte integer
print(arr)
print(f"Datatype : {arr.dtype}")

[[1 2 3]
 [4 5 6]]
Datatype : int32


Shape of array : 

In [19]:
#defines the elements in each dimention
arr=np.array([[1,2,3],[4,5,6]])
print(f'Shape : {arr.shape}')

Shape : (2, 3)


In [25]:
arr=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[11,21,31],[41,51,61]]])
print(f'Shape : {arr.shape}') 
#3 -> elements in outer array
#2 -> elements in 2nd array
#3 -> elements in inner most array 

Shape : (3, 2, 3)


Joining Array : 

In [30]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [41]:
#joining on axis 

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr=np.concatenate((arr1,arr2),axis=1)
print(f'Axis 1 : {arr}')

arr=np.concatenate((arr1,arr2),axis=0)
print(f'Axis 0 : {arr}')

Axis 1 : [[1 2 5 6]
 [3 4 7 8]]
Axis 0 : [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
arr1=np.array([[[1,2],[3,4]],[[11,12],[13,14]]])
arr2=np.array([[[5,6],[7,8]],[[15,16],[17,18]]])

arr=np.concatenate((arr1,arr2),axis=0)
print(f'Axis 0 :\n {arr}')  #all 2d arrays enclosed in single bracket

arr=np.concatenate((arr1,arr2),axis=1)
print(f'\nAxis 1 :\n {arr}') #combine equal index elements into a single 2d array 

arr=np.concatenate((arr1,arr2),axis=2)
print(f'\nAxis 2 :\n {arr}') #combine elements of inner most arrays with equal index 

Axis 0 :
 [[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]

 [[ 5  6]
  [ 7  8]]

 [[15 16]
  [17 18]]]

Axis 1 :
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]]]

Axis 2 :
 [[[ 1  2  5  6]
  [ 3  4  7  8]]

 [[11 12 15 16]
  [13 14 17 18]]]


Splitting array  : 

In [54]:
arr=np.array( [1,2,3,4,5,6])
splitarr=np.array_split(arr,3)

print(splitarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Ravel and Flatten : 

In [71]:
arr= np.array([[[ 1 ,2],[ 3, 4],[ 5, 6],[ 7, 8]],[[11, 12],[13 ,14],[15 ,16],[17, 18]]])

print(f"Dimension : {arr.ndim}")

n= arr.ravel() #converts mulit dimensional array into single 1D array

print(f"New Dimension : {n.ndim}")
print(n)

Dimension : 3
New Dimension : 1
[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]


In [73]:
arr= np.array([[[ 1 ,2],[ 3, 4],[ 5, 6],[ 7, 8]],[[11, 12],[13 ,14],[15 ,16],[17, 18]]])

print(f"Dimension : {arr.ndim}")

n= arr.flatten() #converts mulit dimensional array into single 1D array

print(f"New Dimension : {n.ndim}")
print(n)

Dimension : 3
New Dimension : 1
[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]


In [86]:
arr=np.array([1,2,3,4,5,2,3,4,6,7,8,9,0,8,3,6,1,9,6,4])
uniarr,iarr,countarr=np.unique(arr,return_index=True,return_counts=True)
for i in range(len(uniarr)):
    print(f"\nElement : {uniarr[i]}, Index : {iarr[i]}, Counts : {countarr[i]}");



Element : 0, Index : 12, Counts : 1

Element : 1, Index : 0, Counts : 2

Element : 2, Index : 1, Counts : 2

Element : 3, Index : 2, Counts : 3

Element : 4, Index : 3, Counts : 3

Element : 5, Index : 4, Counts : 1

Element : 6, Index : 8, Counts : 3

Element : 7, Index : 9, Counts : 1

Element : 8, Index : 10, Counts : 2

Element : 9, Index : 11, Counts : 2


Deleting Elements : 

In [95]:
arr=np.array([0,1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18])
d=np.delete(arr,[5,6,7,8]) #[5,6,7,8] indexes of elements to be deleted
print(d)

[ 0  1  2  3  4 11 12 13 14 15 16 17 18]


In [103]:
#multidimentional arrays---
arr=np.array([[1,2,3],[4,5,6]])
d=np.delete(arr,[1],axis=0)
print(f"Axis 0 : {d}")
d=np.delete(arr,[0],axis=1)
print(f"Axis 1 : \n{d}")

Axis 0 : [[1 2 3]]
Axis 1 : 
[[2 3]
 [5 6]]
